services:
    pim_datagrid.product_grid.query.list_attributes:
        class: Oro\Bundle\PimDataGridBundle\Query\Sql\ListAttributesUseableInProductGrid
        arguments:
            - '@database_connection'

    pim_datagrid.product_grid.query.list_attributes_as_column:
        class: Oro\Bundle\PimDataGridBundle\Query\Sql\ListAttributesUseableAsColumnInProductGrid
        arguments:
            - '@database_connection'
